/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocinejungla;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author USUARIO
 */
public class SillasPanel extends javax.swing.JPanel {

    private BD baseDatos = BD.getInstance();
    private static final int INICIO_X_P = 118;
    private static final int INICIO2_X_P = 712;
    private static final int INICIO_X_G = 316;
    private static final int INICIO_Y = 53;
    private static final int DESP_X = 16;
    private static final int DESP_Y = 26;
    private int funcion;

    /**
     * Creates new form Comida
     */
    public SillasPanel(int funcion) {
        
        this.funcion=funcion;
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        imgG = new javax.swing.JLabel();
        labelG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imgG1 = new javax.swing.JLabel();
        labelG1 = new javax.swing.JLabel();
        imgG2 = new javax.swing.JLabel();
        labelG2 = new javax.swing.JLabel();
        imgG3 = new javax.swing.JLabel();
        labelG3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 227, 227));
        setPreferredSize(new java.awt.Dimension(1920, 960));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel2.setText("Elije la silla");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 330, 60));

        jPanel3.setPreferredSize(new java.awt.Dimension(1720, 2000));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sillaG.png"))); // NOI18N
        jPanel3.add(imgG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, 100));

        labelG.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelG.setForeground(new java.awt.Color(0, 0, 0));
        labelG.setText("Silla General");
        jPanel3.add(labelG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 100, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Convencion");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 190, 30));

        imgG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sillaP.png"))); // NOI18N
        jPanel3.add(imgG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 100, 100));

        labelG1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelG1.setForeground(new java.awt.Color(0, 0, 0));
        labelG1.setText("Silla Preferencial");
        jPanel3.add(labelG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 130, 30));

        imgG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sillaS.png"))); // NOI18N
        jPanel3.add(imgG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 100));

        labelG2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelG2.setForeground(new java.awt.Color(0, 0, 0));
        labelG2.setText("Silla Seleccionada");
        jPanel3.add(labelG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 140, 30));

        imgG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sillaO.png"))); // NOI18N
        jPanel3.add(imgG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 100, 100));

        labelG3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelG3.setForeground(new java.awt.Color(0, 0, 0));
        labelG3.setText("Silla Ocupada");
        jPanel3.add(labelG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 120, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 1720, 780));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgG;
    private javax.swing.JLabel imgG1;
    private javax.swing.JLabel imgG2;
    private javax.swing.JLabel imgG3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelG;
    private javax.swing.JLabel labelG1;
    private javax.swing.JLabel labelG2;
    private javax.swing.JLabel labelG3;
    // End of variables declaration//GEN-END:variables

    private static Sala sala = new Sala();

    public static Sala getSala() {
        return sala;
    }

    
    
    public void iniciar() {
        sala = new Sala();
        sala.getAccio().clear();
        sala.getSillas().clear();
        int x = 0;
        int y = 0;
        List<String> sillas = baseDatos.sala(funcion,MainPage.getCineId());
        List<String> numero = new ArrayList<>();
        List<String> tipos = new ArrayList<>();
        List<String> estados = new ArrayList<>();
        for (int i = 0; i < 180; i += 3) {
            numero.add(sillas.get(i));
        }
        for (int i = 1; i < 180; i += 3) {
            tipos.add(sillas.get(i));
        }
        for (int i = 2; i < 180; i += 3) {
            estados.add(sillas.get(i));
        }
        for (int i = 0; i < 60; i++) {
            sala.plantSilla(cambioColumna(numero.get(i)), cambioFila(numero.get(i)), tipos.get(i), estados.get(i));
        }
        
        sala.setBounds(280, 110, 880, 530);
        sala.setVisible(true);
        jPanel3.add(sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 15, 880, 750));

    }

    public int cambioFila(String silla) {
        char columna = silla.charAt(1);
        switch (columna) {
            case 'A':
                return INICIO_Y;
            case 'B':
                return (INICIO_Y + 50 + DESP_Y);
            case 'C':
                return INICIO_Y + ((50 + DESP_Y) * 2);
            case 'D':
                return INICIO_Y + ((50 + DESP_Y) * 3);
            case 'E':
                return INICIO_Y + ((50 + DESP_Y) * 4);
            case 'F':
                return INICIO_Y + ((50 + DESP_Y) * 5);
            case 'G':
                return INICIO_Y + ((50 + DESP_Y) * 6);
            case 'H':
                return INICIO_Y + ((50 + DESP_Y) * 7);
        }
        return 0;

    }

    public int cambioColumna(String silla) {
        char fila = silla.charAt(2);
        int ent = Character.getNumericValue(fila);
        switch (ent) {
            case 1:
                return INICIO_X_P;
            case 2:
                return INICIO_X_P + 50 + DESP_X;
            case 3:
                return INICIO_X_G;
            case 4:
                return INICIO_X_G + DESP_X + 50;
            case 5:
                return INICIO_X_G + ((50 + DESP_X) * 2);
            case 6:
                return INICIO_X_G + ((50 + DESP_X) * 3);
            case 7:
                return INICIO_X_G + ((50 + DESP_X) * 4);
            case 8:
                return INICIO2_X_P;
            case 9:
                return INICIO2_X_P + 50 + DESP_X;
        }
        return 0;

    }

}
